[subsection {Changes for version 0.6}]

[para] In detail:

[list_begin enumerated]
[comment {- - -- --- ----- -------- ------------- ---------------------}]

[enum] This version of [vset PROJECT] requires Tcl 8.6 as a minium runtime.

[enum] In return this version of [vset PROJECT] supports Tcl 9.

[enum] Working with Tcl 8.5 is not guaranteed any longer.

[enum] Keep using [vset PROJECT] 0.5 when working with Tcl 8.5.

[comment {- - -- --- ----- -------- ------------- ---------------------}]
[list_end]
