[comment {--- Standard section and trailer for all manpages in this module --}]
[section {Bugs, Ideas, Feedback}]
[vset TRACKER http://chiselapp.com/user/andreas_kupries/repository/tclyaml]
[vset LABEL   {TclYAML Tracker}]

This document, and the package it describes, will undoubtedly contain
bugs and other problems.

Please report such at the [uri [vset TRACKER] [vset LABEL]].

Please also report any ideas for enhancements you may have for either
package and/or documentation.
