[vset PROJECT TclYAML]
[vset VERSION 0.5]

[comment {- - -- --- ----- -------- ------------- ---------------------
	Central table of links used in the documentation
}]

[vset activestate      [uri https://www.activestate.com ActiveState]]
[vset activetcl        [uri https://www.activestate.com/activetcl ActiveTcl]]
[vset core/tcl         [uri https://core.tcl-lang.org/tcl]]
[vset critcl           [uri https://github.com/andreas-kupries/critcl Critcl]]
[vset fossil           [uri https://www.fossil-scm.org               {Fossil SCM}]]
[vset fossil/get       [uri https://www.fossil-scm.org/download.html {download page}]]
[vset kettle/chisel    [uri https://chiselapp.com/user/andreas_kupries/repository/Kettle]]
[vset kettle/core      [uri https://core.tcl-lang.org/akupries/kettle]]
[vset kettle/github    [uri https://github.com/andreas-kupries/kettle]]
[vset kettle/iguide    [uri https://core.tcl-lang.org/akupries/kettle/doc/trunk/embedded/md/doc/files/kettle_installer.md]]

[vset tclyaml/chisel   [uri https://chiselapp.com/user/andreas_kupries/repository/tclyaml]]
[vset tclyaml/core     [uri https://core.tcl-lang.org/akupries/tclyaml]]
[vset tclyaml/github   [uri https://github.com/andreas-kupries/tclyaml]]
[vset tclyaml/track    [uri https://core.tcl-lang.org/akupries/tclyaml {TclYAML Tracker}]]

[vset teapot           [uri https://teapot.activestate.com]]
[vset yaml             [uri http://yaml.org {YAML Ain't Markup Language}]]
[vset yaml/schema/core [uri https://yaml.org/spec/1.2/spec.html#id2804923 {YAML Core Schema}]]