[vset TCL_version 8.6]
[vset libyaml_version 0.2.5]
[vset PROJECT    TclYAML]
[vset PROJECT_lc tclyaml]
[vset VERSION 0.6]
[comment {
    See also
    - tclyaml.tcl
}]

[comment {- - -- --- ----- -------- ------------- ---------------------
	Central table of links used in the documentation
}]

[vset project/chisel/url   https://chiselapp.com/user/andreas_kupries/repository/tclyaml]
[vset project/core/url     https://core.tcl-lang.org/akupries/tclyaml]
[vset project/github/url   https://github.com/andreas-kupries/tclyaml]

[vset activestate      [uri https://www.activestate.com ActiveState]]
[vset activetcl        [uri https://www.activestate.com/activetcl ActiveTcl]]
[vset core/tcl         [uri https://core.tcl-lang.org/tcl]]
[vset critcl           [uri https://github.com/andreas-kupries/critcl Critcl]]
[vset fossil           [uri https://www.fossil-scm.org               {Fossil SCM}]]
[vset fossil/get       [uri https://www.fossil-scm.org/download.html {download page}]]
[vset kettle/chisel    [uri https://chiselapp.com/user/andreas_kupries/repository/Kettle]]
[vset kettle/core      [uri https://core.tcl-lang.org/akupries/kettle]]
[vset kettle/github    [uri https://github.com/andreas-kupries/kettle]]
[vset kettle/iguide    [uri https://core.tcl-lang.org/akupries/kettle/doc/trunk/embedded/md/doc/files/kettle_installer.md]]

[vset project/chisel   [uri [vset project/chisel/url]]]
[vset project/core     [uri [vset project/core/url]]]
[vset project/github   [uri [vset project/github/url]]]
[vset project/track    [uri [vset project/core/url] {TclYAML Tracker}]]

[vset teapot           [uri https://teapot.activestate.com]]
[vset yaml             [uri http://yaml.org {YAML Ain't Markup Language}]]
[vset yaml/schema/core [uri https://yaml.org/spec/1.2/spec.html#id2804923 {YAML Core Schema}]]
[vset yaml/short       [uri http://yaml.org YAML]]
